### ISSUE TITLE
AttributeError: 'NodeSocketFloatFactor' object has no attribute 'node_tree'

### ISSUE THREAD

**Issue by atticus-lv** [atticus-lv/LightLinkingPanel#4]
After update this morning. light link not available to intitiate.
Latest MacOS , latest blender 4.4
It was working yesterday with blender 4.4

Python: Traceback (most recent call last):
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/panel.py", line 169, in draw
    self.draw_light_list(context, layout)
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/panel.py", line 267, in draw_light_list
    icon, _ = LLP_OT_switch_filter_show.get_icon(context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/ops.py", line 385, in get_icon
    for obj in filter_objects(context):
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/filter.py", line 38, in filter_objects
    for i, v in enumerate(filter_list(context, bitflag=True)):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/filter.py", line 18, in filter_list
    is_show = obj.type == "LIGHT" or check_material_including_emission(obj)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/utils.py", line 327, in check_material_including_emission
    return node_tree_search(out_node) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/utils.py", line 310, in node_tree_search
    find = node_tree_search(from_node, depth + 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/BLENDER/ADDONS etc/addons/ - extensions/blender_org/LightHepler/utils.py", line 320, in node_tree_search
    return node_tree_search(input_point.node_tree, depth + 1)
                            ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NodeSocketFloatFactor' object has no attribute 'node_tree'

![Screenshot 2024-12-24 at 12 25 35 pm](https://github.com/user-attachments/assets/021b5c9c-7e19-4a23-b864-98692e94adca)

_Originally posted by @nurb2kea in https://github.com/AIGODLIKE/LightHelper/issues/3#issuecomment-2561012974_

**Comment by atticus-lv** [comment]
@xmx-emm fix by https://github.com/AIGODLIKE/LightHelper/commit/1e8437fd1e498e8c8e90a83baa4c428da5b658e5

**Comment by xmx-emm** [comment]
https://github.com/AIGODLIKE/LightHelper/releases/tag/v0.3.7
